### ISSUE TITLE
AIF Spec

### ISSUE THREAD

**Issue by joecummings** [joecummings/cdse-covid#123]
- [x] Write out confidence values to `private_data` (dependent on #124)
- [x] Write out ISI CDSE system to AIF
- [x] Add `system` line to AIF triples where necessary
- [x] Format events first as clusters for claim semantics, linked to actual event

```
# Event as cluster
<http://www.isi.edu/gaia/clusters/uiuc/events/L0C04ATIW/EN_Event_004752> a aida:SameAsCluster ;
    aida:prototype <http://www.isi.edu/gaia/events/uiuc/L0C04ATIW/EN_Event_004752> ;
    aida:system <http://www.uiuc.edu> .

# Actual event
<http://www.isi.edu/gaia/events/uiuc/L0C04ATIW/EN_Event_004752> a aida:Event ;
    aida:confidence [ a aida:Confidence ;
            aida:confidenceValue 1e+00 ;
            aida:system <http://www.uiuc.edu> ] ;
    aida:informativeJustification <http://www.isi.edu/gaia/assertions/uiuc/event_informative_justification/EN_Event_004752/L0C04ATIW/2644/2647> ;
    aida:justifiedBy <http://www.isi.edu/gaia/assertions/uiuc/eventjustification/EN_Event_004752/L0C04ATIW/2644/2647> ;
    aida:privateData [ a aida:PrivateData ;
            aida:jsonContent "{\"fileType\": \"en\"}"^^xsd:string ;
            aida:system <http://www.uiuc.edu/fileType> ] ;
    aida:system <http://www.uiuc.edu> .
```

- [x] If we do not find an identity qnode for an entity, assign a `NILX` ID
- [x] Add events and entities to `associatedKEs` field on `Claim` triple
- [x] Add event arguments as `EventArgument` class
- [x] Write out `claim_text`

**Comment by elizlee** [comment]
What do you mean by "Write out `claim_text`"? Is this different from having a `claimText` field in the `Claim` triple?

**Comment by joecummings** [comment]
No, that's the same one, but I see it formatted strangely in the output.

**Comment by elizlee** [comment]
All tasks done, AIF conversion script merged
