### ISSUE TITLE
Fork AMR Utils

### ISSUE THREAD

**Issue by joecummings** [joecummings/cdse-covid#27]
1. Fork AMR Utils to personal or `isi-vista` domain.
2. Change our references in setup to our own AMR Utils instead of the one that may or may not be kept up.

Link: https://github.com/ablodge/amr-utils/tree/master/amr_utils

**Comment by elizlee** [comment]
* New URL: https://github.com/elizlee/amr-utils
* References updated in 78a33dced70555f49ec3f72f6fc3148b5607e736
